import { cn } from "@/components/ui/cn";

/** Generated by scripts/images.mjs; widths that exist for each photo and the source aspect ratio. */
const PHOTOS = {
  hero: { widths: [640, 960], w: 1230, h: 1536 },
  lounge: { widths: [640, 960], w: 1030, h: 1536 },
  tables: { widths: [640, 960, 1280, 1536], w: 1536, h: 1536 },
  coast: { widths: [640, 960], w: 1152, h: 1536 },
} as const;

export type PhotoName = keyof typeof PHOTOS;

export function Photo({
  name,
  alt,
  sizes,
  priority,
  className,
}: {
  name: PhotoName;
  alt: string;
  sizes: string;
  priority?: boolean;
  className?: string;
}) {
  const p = PHOTOS[name];
  const set = (ext: string) => p.widths.map((w) => `/img/${name}-${w}.${ext} ${w}w`).join(", ");
  const largest = p.widths[p.widths.length - 1];
  return (
    <picture className="contents">
      <source type="image/avif" srcSet={set("avif")} sizes={sizes} />
      <source type="image/webp" srcSet={set("webp")} sizes={sizes} />
      <img
        src={`/img/${name}-${largest}.jpg`}
        srcSet={set("jpg")}
        sizes={sizes}
        width={p.w}
        height={p.h}
        alt={alt}
        loading={priority ? "eager" : "lazy"}
        fetchPriority={priority ? "high" : "auto"}
        decoding="async"
        className={cn("h-full w-full object-cover", className)}
      />
    </picture>
  );
}
