import { readFileSync, writeFileSync } from "fs";

const artifact = JSON.parse(
  readFileSync(new URL("../../contracts/out/SetloPackages.sol/SetloPackages.json", import.meta.url), "utf8"),
);
writeFileSync(
  new URL("../lib/abi.ts", import.meta.url),
  `// Generated by scripts/abi.mjs from contracts/out. Do not edit.\nexport const setloAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
);
